package ax.stardust.plainjane.engine

import ax.stardust.plainjane.config.ToolVersions
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

/**
 * Responsible for injecting a custom Plain Jane metadata header into the generated Java models.
 *
 * This class ensures that every generated file is clearly stamped with provenance information.
 * It replaces the default, often verbose, header produced by the underlying OpenAPI Generator
 * engine with a clean, standardized block comment containing tool versions, API metadata,
 * the generation timestamp, and a warning against manual edits.
 *
 * @property toolVersions Contains version metadata for Plain Jane and the underlying engine, used for the header stamp.
 */
class HeaderInjector(
    private val toolVersions: ToolVersions,
) {
    /**
     * Prepends the custom Plain Jane header to the provided Java source code.
     *
     * If the incoming source code already starts with a block comment (which is typically
     * the default header from the underlying generation engine), that entire comment block
     * is stripped away before the new Plain Jane header is applied.
     *
     * @param code The sanitized Java source code string.
     * @param apiTitle The title of the API as parsed from the OpenAPI specification.
     * @param apiVersion The version of the API as parsed from the OpenAPI specification.
     * @return The finalized Java source code string, prepended with the generated header.
     */
    fun inject(
        code: String,
        apiTitle: String,
        apiVersion: String,
    ): String {
        val timestamp = LocalDateTime.now().format(DATE_FORMATTER)
        val header =
            """
            /*
             * Generated by Plain Jane v${toolVersions.plainJaneVersion}
             * 
             * This file was orchestrated by Plain Jane and produced using the
             * OpenAPI Generator engine (v${toolVersions.engineVersion}).
             *
             * API Title:   $apiTitle
             * API Version: $apiVersion
             * Environment: Java 8+
             * Generated:   $timestamp
             *
             * ⚠️ DO NOT EDIT THIS FILE MANUALLY!
             * Any changes will be overwritten the next time the generator runs.
             *
             * For more information or to report issues, visit:
             * https://github.com/rnyholm/plain-jane
             */
            """.trimIndent()

        val resolvedCode =
            code.trim().let {
                if (it.startsWith("/*")) it.substringAfter("*/").trim() else it
            }

        return "$header\n$resolvedCode"
    }

    companion object {
        private val DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")
    }
}
