package ax.stardust.plainjane.engine

import ax.stardust.plainjane.config.RuntimeOptions
import com.github.javaparser.JavaParser
import com.github.javaparser.ParserConfiguration
import com.github.javaparser.ast.body.FieldDeclaration
import com.github.javaparser.ast.expr.MarkerAnnotationExpr
import com.github.javaparser.ast.expr.NormalAnnotationExpr
import com.github.javaparser.ast.expr.SingleMemberAnnotationExpr
import com.github.javaparser.ast.visitor.ModifierVisitor
import com.github.javaparser.ast.visitor.Visitable
import java.io.File

/**
 * The core cleaning engine responsible for stripping heavy framework dependencies from the generated code.
 *
 * Plain Jane's primary goal is to produce dependency-free, pure Java models. This class achieves
 * that by parsing the generated Java files into an Abstract Syntax Tree (AST) using JavaParser.
 * It then traverses the tree using the Visitor pattern to safely remove unwanted annotations
 * (like `@JsonProperty`, `@Schema`), internal OpenAPI constants, and their corresponding imports,
 * while preserving standard Java syntax and allowed annotations.
 *
 * @property runtimeOptions Defines runtime behaviors, such as enabling verbose debug output for parsing errors.
 * @property log A logging function to report warnings or errors during the AST manipulation.
 */
class JavaSanitizer(
    private val runtimeOptions: RuntimeOptions,
    private val log: (String) -> Unit,
) {
    /**
     * Encapsulates the outcome of a single file's sanitization process.
     *
     * @property code The final Java source code string. If [isSanitized] is true, this is the cleaned code.
     * If false, it falls back to the original, unmodified file content.
     * @property isSanitized Indicates whether the AST manipulation was successful.
     */
    data class Result(
        val code: String,
        val isSanitized: Boolean,
    )

    /**
     * Parses, traverses, and sanitizes the provided Java file.
     *
     * This method reads the raw file and constructs an AST. If the generated code contains invalid
     * Java syntax, it gracefully falls back to returning the raw source code. During a successful
     * traversal, it strips out all annotations not explicitly listed in [ALLOWED_ANNOTATIONS],
     * removes internal generator fields (e.g., `JSON_PROPERTY_...`), and cleans up orphaned imports.
     *
     * @param file The physical Java file generated by the underlying OpenAPI engine.
     * @return A [Result] object containing the processed code and a success flag.
     */
    fun sanitize(file: File): Result {
        // just to be sure to parse according to java 8
        val parserConfig = ParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_8)
        val parser = JavaParser(parserConfig)

        return try {
            val parsedFile = parser.parse(file)
            if (!parsedFile.isSuccessful) {
                log(
                    appendDebugHintIfNeeded(
                        "${UI.WARNING} Warning: OpenAPI Generator generated invalid Java syntax for ${file.name}. Skipping sanitization",
                    ),
                )

                if (runtimeOptions.debug) {
                    val reasons =
                        parsedFile.problems.joinToString("\n") { problem ->
                            buildString {
                                append("   - ${problem.message}")

                                problem.location.ifPresent { loc ->
                                    loc.toRange().ifPresent { range ->
                                        append(" [Line: ${range.begin.line}, Col: ${range.begin.column}]")
                                    }
                                }

                                problem.cause.ifPresent { cause ->
                                    val cleanCause = cause.message?.replace(Regex("\\s+"), " ")?.trim()
                                    if (cleanCause != null) {
                                        append(" | Cause: $cleanCause")
                                    }
                                }
                            }
                        }
                    log("   -> Reason: $reasons")
                }

                return Result(code = file.readText(), isSanitized = false)
            }

            // sanitize AST tree using visitor pattern which will effectively remove all annotations
            // and field declarations in one single pass
            val compilationUnit = parsedFile.result.get()
            compilationUnit.accept(
                object : ModifierVisitor<Void?>() {
                    // simple annotations like, @Generated
                    override fun visit(
                        n: MarkerAnnotationExpr,
                        arg: Void?,
                    ): Visitable? = if (n.nameAsString in ALLOWED_ANNOTATIONS) super.visit(n, arg) else null

                    // annotations with a single value, like @SuppressWarnings("...")
                    override fun visit(
                        n: SingleMemberAnnotationExpr,
                        arg: Void?,
                    ): Visitable? = if (n.nameAsString in ALLOWED_ANNOTATIONS) super.visit(n, arg) else null

                    // complex annotations with multiple values, like @JsonProperty(value = "...")
                    override fun visit(
                        n: NormalAnnotationExpr,
                        arg: Void?,
                    ): Visitable? = if (n.nameAsString in ALLOWED_ANNOTATIONS) super.visit(n, arg) else null

                    // field declarations
                    override fun visit(
                        n: FieldDeclaration,
                        arg: Void?,
                    ): Visitable? {
                        val isInternalConstant = n.variables.any { it.nameAsString.startsWith("JSON_PROPERTY_") }
                        return if (isInternalConstant) null else super.visit(n, arg)
                    }
                },
                null,
            )

            // remove unnecessary imports that are no longer needed after removing annotations and fields,
            // such as Jackson, Jakarta, Swagger, etc.
            compilationUnit.imports.removeIf { import ->
                UNWANTED_PACKAGES.any { unwantedPackage -> import.nameAsString.startsWith(unwantedPackage) }
            }

            Result(code = compilationUnit.toString(), isSanitized = true)
        } catch (e: Exception) {
            log(
                appendDebugHintIfNeeded(
                    "${UI.WARNING} Warning: Unexpected error while manipulating AST for ${file.name}. Skipping sanitization",
                ),
            )
            if (runtimeOptions.debug) {
                log("   -> Reason: ${e.javaClass.simpleName}: ${e.message}")
            }

            Result(code = file.readText(), isSanitized = false)
        }
    }

    private fun appendDebugHintIfNeeded(message: String): String {
        val suffix = if (runtimeOptions.debug) "." else " (run with --debug for details)."
        return "$message$suffix"
    }

    companion object {
        /**
         * A safelist of annotations that should survive the sanitization process.
         */
        val ALLOWED_ANNOTATIONS =
            setOf(
                "Override",
                "Deprecated",
                "SuppressWarnings",
            )

        /**
         * A denylist of package prefixes. Any import statement starting with these will be removed.
         */
        val UNWANTED_PACKAGES =
            listOf(
                "com.fasterxml.jackson",
                "org.openapitools",
                "jakarta.annotation",
                "jakarta.validation",
                "io.swagger",
                "javax.annotation",
                "javax.validation",
            )
    }
}
