package ax.stardust.plainjane.engine

import ax.stardust.plainjane.UI
import ax.stardust.plainjane.config.IOConfig
import ax.stardust.plainjane.config.ModelConfig
import ax.stardust.plainjane.config.RuntimeOptions
import ax.stardust.plainjane.config.ToolVersions
import io.swagger.parser.OpenAPIParser
import io.swagger.v3.parser.core.models.ParseOptions
import org.openapitools.codegen.DefaultGenerator
import org.openapitools.codegen.config.CodegenConfigurator
import java.io.File
import java.io.OutputStream
import java.io.PrintStream
import java.util.logging.Level
import java.util.logging.Logger

/**
 * The core wrapper around the external OpenAPI Generator engine.
 *
 * This class abstracts the complexities of the underlying code generator (OpenAPI Generator)
 * and its parsers (Swagger Parser). It acts as the first stage in the generation pipeline by
 * ingesting an OpenAPI specification and outputting raw, un-sanitized Java models.
 * * It takes special care to isolate the noisy internal logging and standard output streams
 * of the underlying engine to maintain a clean Developer Experience (DX) in the terminal,
 * unless debug mode is explicitly activated.
 *
 * @property ioConfig Configuration for input (spec URI) and output directories.
 * @property modelConfig Configuration for the generated domain models (e.g., target package name).
 * @property runtimeOptions Controls execution behavior, such as toggling verbose debug logging.
 * @property toolVersions Metadata about the generator versions.
 * @property artifactId The Maven artifact ID, used here primarily for contextual logging.
 * @property log A logging function to report engine progress back to the user.
 */
class OpenApiEngine(
    private val ioConfig: IOConfig,
    private val modelConfig: ModelConfig,
    private val runtimeOptions: RuntimeOptions,
    private val toolVersions: ToolVersions,
    private val artifactId: String,
    private val log: (String) -> Unit,
) {
    /**
     * The title of the API as parsed from the OpenAPI specification's `info.title` field.
     * Defaults to "Unknown API" if parsing fails or before generation starts.
     */
    var apiTitle: String = "Unknown API"
        private set

    /**
     * The version of the API as parsed from the OpenAPI specification's `info.version` field.
     * Defaults to "Unknown Version" if parsing fails or before generation starts.
     */
    var apiVersion: String = "Unknown Version"
        private set

    /**
     * The list of physical Java files successfully generated by the underlying engine.
     * This list only contains the relevant model files; ignored packages and artifacts are filtered out.
     */
    var generatedJavaFiles: List<File> = emptyList()
        private set

    init {
        configureLogging()
    }

    private fun configureLogging() {
        if (runtimeOptions.debug) {
            // if debug all logging is enabled to see the raw output from the OpenAPI Generator engine
            val rootLogger = Logger.getLogger("")
            rootLogger.level = Level.ALL
            rootLogger.handlers.forEach { it.level = Level.ALL }

            System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "debug")

            log("${UI.BUG} Debug mode enabled - showing underlying engine logs")
        } else {
            // silence the OpenAPI Generator's internal logging to avoid cluttering the output
            System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "error")

            val loggersToMute =
                listOf(
                    "io.swagger.v3.parser.OpenAPIV3Parser",
                    "org.openapitools.codegen.config.CodegenConfigurator",
                    "org.openapitools.codegen.DefaultGenerator",
                    "org.openapitools.codegen.AbstractGenerator",
                    "org.openapitools.codegen.DefaultCodegen",
                )

            loggersToMute.forEach { loggerName ->
                Logger.getLogger(loggerName).level = Level.SEVERE
            }
        }
    }

    /**
     * Parses the OpenAPI specification and triggers the generation of raw Java models.
     *
     * This method resolves references within the spec, extracts API metadata ([apiTitle], [apiVersion]),
     * and configures the `CodegenConfigurator` to produce native Java models.
     * It temporarily redirects standard streams to `null` to suppress hardcoded output from
     * the OpenAPI Generator, ensuring only relevant application logs are printed unless debug mode is active.
     *
     * @throws IllegalArgumentException If the provided OpenAPI specification is invalid or cannot be parsed.
     */
    @Suppress("ktlint:standard:comment-wrapping")
    fun generateRawModels() {
        log("${UI.ROCKET} Starting generation for $artifactId using OpenAPI Generator engine (v${toolVersions.engineVersion})...")

        // configure parser by having it to solve references automatically
        val parseOptions =
            ParseOptions().apply {
                isResolve = true
            }

        // use readLocation instead of a simple read just to get any messages in case of errors and warnings
        // handle any messages accordingly
        val parseResult =
            OpenAPIParser().readLocation(
                /* url = */ ioConfig.input.uri,
                /* auth = */ null,
                /* options = */ parseOptions,
            )
        if (!parseResult.messages.isNullOrEmpty()) {
            log("${UI.WARNING}️ OpenAPI Specification issues found in ${ioConfig.input.name}:")

            if (runtimeOptions.debug) {
                val reasons = parseResult.messages.joinToString("\n") { "   - ${it.trim()}" }
                log("   -> Reason:\n$reasons")
            }
        }

        // get open api from result in order to get title and version from specification
        val openApi =
            parseResult.openAPI ?: throw IllegalArgumentException(
                buildString {
                    append("Failed to parse OpenAPI specification from ${ioConfig.input.name}. ")
                    append("Ensure it is a valid OpenAPI v2/v3 document (JSON/YAML).\n")

                    val reasons =
                        parseResult.messages
                            ?.filter { it.isNotBlank() }
                            ?.joinToString("\n") { "   - ${it.trim()}" }

                    if (!reasons.isNullOrEmpty()) {
                        append("   -> Reason:\n$reasons")
                    } else {
                        append("   -> Reason:\n   - Unknown parsing error (check file formatting and syntax).")
                    }
                },
            )

        apiTitle = openApi.info?.title ?: ioConfig.input.name
        apiVersion = openApi.info?.version ?: "unknown"

        // configure the OpenAPI Generator with desired settings
        val configurator =
            CodegenConfigurator().apply {
                // specify the input spec and output directory as well as the packages
                setInputSpec(ioConfig.input.uri)
                setOutputDir(ioConfig.output.absolutePath)
                setGeneratorName("java")
                setPackageName(modelConfig.pkg)
                setModelPackage(modelConfig.pkg)

                // "dummy" packages for things we will delete/disable anyway
                setApiPackage("ignore")
                setInvokerPackage("ignore")

                // ignore validation errors in the spec, like license-errors etc.
                setValidateSpec(false)

                // disable generation of APIs, invokers, supporting files, docs, and tests since we only want models
                addGlobalProperty("models", "")
                addGlobalProperty("apis", "false")
                addGlobalProperty("invokers", "false")
                addGlobalProperty("supportingFiles", "false")
                addGlobalProperty("modelDocs", "false")
                addGlobalProperty("modelTests", "false")

                // java config
                setLibrary("native")
                addAdditionalProperty("dateLibrary", "java8")
                addAdditionalProperty("openApiNullable", "false")
                addAdditionalProperty("useJakartaEe", "true") // this will be cleaned out later, but the engine needs to know
                addAdditionalProperty("hideGenerationTimestamp", "true")
                addAdditionalProperty("sortModelPropertiesByRequiredFlag", "false")
                addAdditionalProperty("legacyDiscriminatorBehavior", "false")
                addAdditionalProperty("supportUrlQuery", "false")
            }

        // temporarily mute standard streams to silence OpenAPI Generator's hardcoded console spam
        // we isolate this exactly around the execution to avoid swallowing our own CLI logs
        val originalOut = System.out
        val originalErr = System.err
        if (!runtimeOptions.debug) {
            // send system.out/err to a "black hole" during generation to suppress logs from the OpenAPI Generator engine
            val nullStream = PrintStream(OutputStream.nullOutputStream())
            System.setOut(nullStream)
            System.setErr(nullStream)
        }

        // generate the raw files using the OpenAPI Generator engine
        val allGeneratedFiles =
            try {
                val clientOptInput = configurator.toClientOptInput()
                DefaultGenerator().opts(clientOptInput).generate()
            } finally {
                System.setOut(originalOut)
                System.setErr(originalErr)
            }

        // filter out generated files that we're really interested in
        generatedJavaFiles =
            allGeneratedFiles.filter { file ->
                val isJavaFile = file.extension == "java"
                val isIgnored =
                    file.absolutePath.contains("${File.separator}ignore${File.separator}") ||
                        file.absolutePath.contains("${File.separator}api${File.separator}")
                isJavaFile && !isIgnored
            }

        log("${UI.CHECK} Raw generation completed")
    }

    /**
     * Purges unnecessary files and directories created by the underlying OpenAPI Generator.
     *
     * The generator often produces build scripts (Gradle, maven), CI configuration files (.github, .travis),
     * and documentation stubs by default, even when disabled in the configuration. This method acts as a
     * post-generation sweeper to ensure the output directory only contains the assets strictly requested by the user.
     */
    fun removeBloat() {
        // start clean up of all the extra files and folders that the OpenAPI Generator creates, but we don't want in our output
        log("${UI.TRASH} Removing bloat generated by OpenAPI Generator (.github, api, gradle, etc.)...")

        // list of files and directories that we want to completely remove from the
        // output and remove them if they exist
        val filesAndDirectoriesToRemove =
            listOf(
                "src",
                "api",
                ".github",
                ".openapi-generator",
                "gradle",
                "gradlew",
                "gradlew.bat",
                "bin",
                ".travis.yml",
                "git_push.sh",
            )

        filesAndDirectoriesToRemove.forEach { fileOrDirectory ->
            val file = File(ioConfig.output, fileOrDirectory)
            if (file.exists()) {
                if (file.isDirectory) {
                    file.deleteRecursively()
                } else {
                    file.delete()
                }
            }
        }
    }
}
