package ax.stardust.plainjane.engine

import ax.stardust.plainjane.TestData.API_TITLE
import ax.stardust.plainjane.TestData.API_VERSION
import ax.stardust.plainjane.TestData.OPENAPI_GENERATOR_VERSION
import ax.stardust.plainjane.TestData.PLAIN_JANE_VERSION
import ax.stardust.plainjane.config.ToolVersions
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import kotlin.test.assertContains
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class HeaderInjectorTest {
    private lateinit var toolVersions: ToolVersions
    private lateinit var injector: HeaderInjector

    @BeforeEach
    fun setup() {
        toolVersions =
            ToolVersions(
                plainJaneVersion = PLAIN_JANE_VERSION,
                engineVersion = OPENAPI_GENERATOR_VERSION,
            )
        injector = HeaderInjector(toolVersions = toolVersions)
    }

    @Test
    fun `should inject header and preserve original code when no existing header is present`() {
        val originalCode = "public class MyModel {\n    private String id;\n}"

        val result = injector.inject(code = originalCode, apiTitle = API_TITLE, apiVersion = API_VERSION)

        // verify placement of header and original code
        assertTrue(result.startsWith("/*"), "Result should start with a block comment")
        assertTrue(result.endsWith(originalCode), "Original code should be preserved at the end")
    }

    @Test
    fun `should strip existing block comment header before injecting new header`() {
        val originalCode =
            """
            /*
             * This is an ugly default OpenAPI Generator header.
             * It contains formatting we don't want.
             */
            package com.example.models;
            
            public class MyModel {}
            """.trimIndent()

        val expectedCodePart = "package com.example.models;\n\npublic class MyModel {}"

        val result = injector.inject(code = originalCode, apiTitle = API_TITLE, apiVersion = API_VERSION)

        // verify that the old header is gone
        assertFalse(result.contains("ugly default OpenAPI Generator header"))

        // verify that the new header is at the top and the original code (minus old header) is at the bottom
        assertTrue(result.endsWith(expectedCodePart))
        assertContains(result, "Generated by Plain Jane")
    }

    @Test
    fun `should not strip inline comments at the start of the code`() {
        // if the code starts with a normal inline comment, it should be preserved
        val originalCode =
            """
            // This is a normal comment
            public class MyModel {}
            """.trimIndent()

        val result = injector.inject(code = originalCode, apiTitle = API_TITLE, apiVersion = API_VERSION)

        // verify survival of inline comment and correct placement of header
        assertContains(result, "// This is a normal comment")
        assertTrue(result.endsWith("public class MyModel {}"))
    }

    @Test
    fun `should inject correct metadata and current timestamp into the header`() {
        val result = injector.inject(code = "class A {}", apiTitle = API_TITLE, apiVersion = API_VERSION)

        // verify metadata of header
        assertContains(result, "Generated by Plain Jane v$PLAIN_JANE_VERSION")
        assertContains(result, "engine (v$OPENAPI_GENERATOR_VERSION)")
        assertContains(result, "API Title:   $API_TITLE")
        assertContains(result, "API Version: $API_VERSION")
        assertContains(result, "⚠️ DO NOT EDIT THIS FILE MANUALLY!")

        // verify that the generated date
        val today = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))
        assertContains(result, "Generated:   $today")
    }

    @Test
    fun `should handle empty code strings gracefully`() {
        val result = injector.inject(code = "", apiTitle = API_TITLE, apiVersion = API_VERSION)

        // verify that the result is not empty and contains the header, even if the input code is empty
        assertTrue(result.startsWith("/*"))
        assertContains(result, "Generated by Plain Jane v$PLAIN_JANE_VERSION")
    }
}
