package ax.stardust.plainjane

import ax.stardust.plainjane.TestData.PACKAGE_NAME
import ax.stardust.plainjane.cli.PlainJaneCommand
import com.github.ajalt.clikt.testing.test
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class PlainJaneE2ETest {
    @Test
    fun `should run full pipeline and produce multiple clean java models with complex types`(
        @TempDir tempDir: File,
    ) {
        val specFileName = "e2e-spec.yaml"
        val resourceUrl =
            this::class.java.classLoader.getResource(specFileName)
                ?: throw IllegalStateException("Could not find $specFileName in test resources")
        val specFile = File(resourceUrl.toURI())

        val outputDir = File(tempDir, "output")

        // run the CLI with the test spec and capture the result
        val result =
            PlainJaneCommand().test(
                listOf(
                    "-i",
                    specFile.absolutePath,
                    "-o",
                    outputDir.absolutePath,
                    "-p",
                    PACKAGE_NAME,
                    "--scaffold",
                    "-a",
                    "petstore-models",
                ),
            )

        // verify that the CLI process exited successfully
        assertEquals(0, result.statusCode, "CLI should exit with status 0. Error: ${result.stderr}")

        // verify that the pom.xml and README.md files exists in the output directory as expected
        assertTrue(File(outputDir, "pom.xml").exists(), "pom.xml should exist")
        assertTrue(File(outputDir, "README.md").exists(), "README.md should exist")

        // verify that the expected package directory structure was created
        val expectedModelDir = File(outputDir, PACKAGE_NAME.replace('.', File.separatorChar))
        assertTrue(expectedModelDir.exists() && expectedModelDir.isDirectory, "Package directory structure should exist")

        // verify that both Pet.java and Tag.java were generated
        val petFile = File(expectedModelDir, "Pet.java")
        val tagFile = File(expectedModelDir, "Tag.java")
        assertTrue(petFile.exists(), "Pet.java should exist")
        assertTrue(tagFile.exists(), "Tag.java should exist")

        // Assert - "CSI: JavaSanitizer" - Dags att inspektera koden i Pet.java
        val petCode = petFile.readText()

        // verify header and package declaration
        assertContains(petCode, "Generated by Plain Jane")
        assertContains(petCode, "package $PACKAGE_NAME;")

        // verify that standard Java imports are preserved
        assertContains(petCode, "import java.util.List;")
        assertContains(petCode, "import java.time.LocalDate;")
        assertContains(petCode, "import java.time.OffsetDateTime;")

        // verify enum declaration and values
        assertContains(petCode, "public enum StatusEnum")
        assertContains(petCode, "AVAILABLE(String.valueOf(\"AVAILABLE\"))")

        // verify that complex types like List<Tag>, LocalDate, and OffsetDateTime are declared correctly
        assertContains(petCode, "private List<Tag> tags = new ArrayList<>();")
        assertContains(petCode, "private LocalDate birthDate;")
        assertContains(petCode, "private OffsetDateTime createdAt;")

        // verify that the generated code is clean and does not contain any unwanted annotations, fields, or imports
        assertFalse(petCode.contains("@JsonProperty"), "Code is contaminated with @JsonProperty")
        assertFalse(petCode.contains("@Schema"), "Code is contaminated with @Schema")
        assertFalse(petCode.contains("import com.fasterxml.jackson"), "Code is contaminated with Jackson imports")
        assertFalse(petCode.contains("import io.swagger"), "Code is contaminated with Swagger imports")
        assertFalse(petCode.contains("JSON_PROPERTY_"), "Code is contaminated with internal generator constants")
    }
}
