package ax.stardust.plainjane

import ax.stardust.plainjane.TestData.PACKAGE_NAME
import ax.stardust.plainjane.cli.PlainJaneCommand
import com.github.ajalt.clikt.testing.test
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File
import javax.tools.DiagnosticCollector
import javax.tools.JavaFileObject
import javax.tools.ToolProvider
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class PlainJaneE2ETest {
    @Test
    fun `should run full pipeline and produce multiple clean java models with complex types`(
        @TempDir tempDir: File,
    ) {
        val specFileName = "e2e-spec.yaml"
        val resourceUrl =
            this::class.java.classLoader.getResource(specFileName)
                ?: throw IllegalStateException("Could not find $specFileName in test resources")
        val specFile = File(resourceUrl.toURI())

        val outputDir = File(tempDir, "output")

        // run the CLI with the test spec and capture the result
        val result =
            PlainJaneCommand().test(
                listOf(
                    "-i",
                    specFile.absolutePath,
                    "-o",
                    outputDir.absolutePath,
                    "-p",
                    PACKAGE_NAME,
                    "--scaffold",
                    "-a",
                    "petstore-models",
                ),
            )

        // verify that the CLI process exited successfully
        assertEquals(0, result.statusCode, "CLI should exit with status 0. Error: ${result.stderr}")

        // verify that the pom.xml and README.md files exists in the output directory as expected
        assertTrue(File(outputDir, "pom.xml").exists(), "pom.xml should exist")
        assertTrue(File(outputDir, "README.md").exists(), "README.md should exist")

        // verify that the expected package directory structure was created
        val expectedModelDir = File(outputDir, PACKAGE_NAME.replace('.', File.separatorChar))
        assertTrue(expectedModelDir.exists() && expectedModelDir.isDirectory, "Package directory structure should exist")

        val petFile = File(expectedModelDir, "Pet.java")
        val customTagsFile = File(expectedModelDir, "CustomTags.java")
        val animalFile = File(expectedModelDir, "Animal.java")

        assertTrue(petFile.exists(), "Pet.java should exist")
        assertTrue(customTagsFile.exists(), "CustomTags.java should exist")
        assertTrue(animalFile.exists(), "Animal.java should exist")

        val petCode = petFile.readText()

        // verify header, package and standard imports
        assertContains(petCode, "Generated by Plain Jane")
        assertContains(petCode, "package $PACKAGE_NAME;")
        assertContains(petCode, "import java.util.List;")
        assertContains(petCode, "import java.time.LocalDate;")
        assertContains(petCode, "import java.time.OffsetDateTime;")

        // verify enum declaration and values
        assertContains(petCode, "public enum StatusEnum")
        assertContains(petCode, "AVAILABLE(\"AVAILABLE\")")

        // verify Gson adapter inside enums should be removed
        assertFalse(petCode.contains("public static class Adapter extends TypeAdapter"), "Gson enum Adapter was not removed")

        // verify HashMap assignment should be fixed
        assertTrue(petCode.contains("private CustomTags metadata = new CustomTags();"), "HashMap bug was not fixed in VariableDeclarator")
        assertFalse(petCode.contains("new HashMap<>()"), "HashMap bug is still present")

        // verify that the generated code is clean and does not contain any unwanted annotations, fields, or imports
        assertFalse(petCode.contains("@JsonProperty"), "Code is contaminated with @JsonProperty")
        assertFalse(petCode.contains("@Schema"), "Code is contaminated with @Schema")
        assertFalse(petCode.contains("import com.fasterxml.jackson"), "Code is contaminated with Jackson imports")
        assertFalse(petCode.contains("import io.swagger"), "Code is contaminated with Swagger imports")
        assertFalse(petCode.contains("JSON_PROPERTY_"), "Code is contaminated with internal generator constants")

        // verify CustomTypeAdapterFactory should be removed from CustomTags
        val customTagsCode = customTagsFile.readText()
        assertFalse(customTagsCode.contains("CustomTypeAdapterFactory"), "Gson CustomTypeAdapterFactory was not removed")

        // verify Animal should be a clean interface
        val animalCode = animalFile.readText()
        assertTrue(animalCode.contains("public interface Animal"), "Polymorphic base class was not converted to interface")
        assertFalse(animalCode.contains("AbstractOpenApiSchema"), "AbstractOpenApiSchema inheritance was not removed")

        // compile the code programmatically
        val allJavaFiles = expectedModelDir.listFiles { _, name -> name.endsWith(".java") }?.toList() ?: emptyList()
        assertTrue(allJavaFiles.isNotEmpty(), "No Java files found to compile")

        val compiler = ToolProvider.getSystemJavaCompiler()
        val diagnostics = DiagnosticCollector<JavaFileObject>()
        val fileManager = compiler.getStandardFileManager(diagnostics, null, null)

        val compilationUnits = fileManager.getJavaFileObjectsFromFiles(allJavaFiles)
        val task = compiler.getTask(null, fileManager, diagnostics, null, null, compilationUnits)

        val success = task.call()

        if (!success) {
            val errors =
                diagnostics.diagnostics.joinToString("\n") { diagnostic ->
                    "Error on line ${diagnostic.lineNumber} in ${diagnostic.source?.name}: ${diagnostic.getMessage(null)}"
                }
            throw AssertionError("The generated code failed to compile natively!\n$errors")
        }

        fileManager.close()
    }
}
