package ax.stardust.plainjane

import ax.stardust.plainjane.engine.ExtrasGenerator
import ax.stardust.plainjane.engine.HeaderInjector
import ax.stardust.plainjane.engine.JavaSanitizer
import ax.stardust.plainjane.engine.OpenApiEngine
import ax.stardust.plainjane.engine.WorkspaceInitializer
import java.io.File
import java.util.concurrent.atomic.AtomicInteger

/**
 * The central orchestrator for the Plain Jane model generation pipeline.
 *
 * This class acts as a Facade, coordinating the various specialized engines and tools
 * to produce clean, dependency-free Java models from an OpenAPI specification. It handles
 * the entire lifecycle: from workspace preparation and raw code generation, to parallel
 * AST sanitization, header injection, file moving, and finally generating extra project files.
 *
 * @property workspace Initializes and prepares the directory structure.
 * @property engine The underlying OpenAPI generator engine that produces the raw models.
 * @property sanitizer Parses and cleans the raw Java code (removes framework annotations etc.).
 * @property headerInjector Injects the Plain Jane metadata header into the sanitized files.
 * @property extrasGenerator Generates additional project files like `pom.xml` and `README.md`.
 * @property log A logging function to report progress back to the caller (e.g., the CLI).
 */
class ModelOrchestrator(
    private val workspace: WorkspaceInitializer,
    private val engine: OpenApiEngine,
    private val sanitizer: JavaSanitizer,
    private val headerInjector: HeaderInjector,
    private val extrasGenerator: ExtrasGenerator,
    private val log: (String) -> Unit,
) {
    /**
     * Encapsulates the final outcome of the orchestration process.
     *
     * @property totalCount The total number of raw Java files generated by the underlying engine.
     * @property sanitizedCount The number of files successfully sanitized and processed.
     * @property failedCount The number of files that failed sanitization (usually due to parsing errors).
     */
    data class Result(
        val totalCount: Int,
        val sanitizedCount: Int,
        val failedCount: Int,
    )

    /**
     * Executes the full generation and sanitization pipeline.
     *
     * The orchestration follows a strict sequence:
     * 1. Initializes the target workspace.
     * 2. Generates raw Java models using the OpenAPI engine.
     * 3. Processes all generated files in parallel (sanitizing, injecting headers, and moving to the final package directory).
     * 4. Cleans up unnecessary bloat generated by the engine.
     * 5. Generates optional extra files (e.g., POM, README, .gitignore).
     *
     * @return A [Result] containing the statistics of the orchestration run.
     */
    fun orchestrate(): Result {
        workspace.initialize()
        engine.generateRawModels()

        log("${UI.SOAP} Sanitizing and moving models...")

        // we handle the sanitization and file writing in parallel hence the need for thread safety
        val sanitizedCount = AtomicInteger(0)
        val failedCount = AtomicInteger(0)

        engine.generatedJavaFiles.parallelStream().forEach { file ->
            // sanitize the generated code and inject header if sanitization was successful
            val sanitationResult = sanitizer.sanitize(file)
            val finalCode =
                if (sanitationResult.isSanitized) {
                    headerInjector.inject(
                        code = sanitationResult.code,
                        apiTitle = engine.apiTitle,
                        apiVersion = engine.apiVersion,
                    )
                } else {
                    sanitationResult.code
                }

            // create the final file in correct destination and write the sanitized code to it,
            File(workspace.packageDir, file.name).writeText(finalCode)

            if (sanitationResult.isSanitized) {
                sanitizedCount.incrementAndGet()
            } else {
                failedCount.incrementAndGet()
            }
        }

        engine.removeBloat()
        extrasGenerator.generate(apiTitle = engine.apiTitle, apiVersion = engine.apiVersion)

        return Result(
            totalCount = engine.generatedJavaFiles.size,
            sanitizedCount = sanitizedCount.get(),
            failedCount = failedCount.get(),
        )
    }
}
